services:
  server-development:
    container_name: golf-server
    build:
      context: server
      dockerfile: Dockerfile
      target: development
      args:
        RUST_TARGET: ${RUST_TARGET:?need to know cpu architecture for server musl build}
    restart: unless-stopped
    environment:
      RUST_LOG: "1"
      RUST_BACKTRACE: "1"
    volumes:
      - ./server/backend:/app/backend
    networks:
      - internal
    profiles:
      - development

  reverse-proxy-development:
    container_name: golf-reverse-proxy
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
      - external
    ports:
      - "80:80"
    profiles:
      - development
