services:
  server-development:
    container_name: golf-server
    build:
      context: server
      dockerfile: Dockerfile
      target: development
      args:
        RUST_TARGET: ${RUST_TARGET:?need to know cpu architecture for server musl build}
    restart: unless-stopped
    volumes:
      - ./server/backend:/app/backend
    networks:
      - internal
    profiles:
      - development

  reverse-proxy-development:
    container_name: counter-reverse-proxy
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - server-development
    restart: unless-stopped
    networks:
      - internal
      - external
    ports:
      - "80:80"
    profiles:
      - development

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
