services:
  server-production:
    container_name: golf-server
    build:
      context: server
      dockerfile: Dockerfile
      target: production
      args:
        RUST_TARGET: ${RUST_TARGET:?need to know cpu architecture for server musl build}
    restart: unless-stopped
    profiles:
      - production

# ClusterIP is default network and is already internal to the cluster
