services:
  server-production:
    container_name: golf-server
    build:
      context: server
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    profiles:
      - production

# ClusterIP is default network and is already internal to the cluster
