x-dev-environment: &dev-env
  RUST_LOG: "1"
  RUST_BACKTRACE: "1"

x-dev-volumes: &dev-volumes
  - ./server/backend:/app/backend

services:
  server-development:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
      target: development
      args:
        RUST_TARGET: ${RUST_TARGET:?need to know cpu architecture for server musl build}
    restart: unless-stopped
    environment:
      <<: *dev-env
    volumes: *dev-volumes
    networks:
      - internal
    profiles:
      - development

  reverse-proxy-development:
    container_name: reverse-proxy
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
      - external
    ports:
      - "80:80"
    profiles:
      - development
