x-dev-environment: &dev-env
  RUST_LOG: "1"
  RUST_BACKTRACE: "1"

x-dev-volumes: &dev-volumes
  - ./server/src:/app/src
  - ./server/static:/app/static
  - ./server/templates:/app/templates

services:
  # development services
  
  server-development:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
      target: development
      args:
        RUST_TARGET: ${RUST_TARGET}
    restart: unless-stopped
    environment:
      <<: *dev-env
    volumes: *dev-volumes
    networks:
      - internal
    profiles:
      - development

  reverse-proxy-development:
    container_name: reverse-proxy
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
      - external
    ports:
      - "80:80"
    profiles:
      - development

  # production services

  server-production:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
      target: production
      args:
        RUST_TARGET: ${RUST_TARGET}
    restart: unless-stopped
    networks:
      - internal
    profiles:
      - production

  reverse-proxy-production:
    container_name: reverse-proxy
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
      - external
    profiles:
      - production

  cloudflared-production:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - external
    command: tunnel --no-autoupdate run
    profiles:
      - production

networks:
  internal:
    driver: bridge
  external:
    driver: bridge