services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - "3000:3000"

  reverse-proxy:
    image: nginx:alpine
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # readonly mount our proxy
    ports:
      - "80:80"
      #- "443:443" # uncomment if we want to handle ssl/tls, for now we delegate
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
