services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      target: development # either development or production
    # disable these volumes when using production
    # - could use an environment variable that we only set for develop builds
    volumes:
      - ./server/src:/app/src
      - ./server/static:/app/static
      - ./server/templates:/app/templates
    networks:
      - internal
    environment:
      - RUST_LOG=1
      - RUST_BACKTRACE=1

  reverse-proxy:
    image: nginx:alpine
    depends_on:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # readonly mount our proxy
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
