services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      target: production # either development or production
    environment:
      - RUST_LOG=1
      - RUST_BACKTRACE=1
    # disable these volumes when using production
    #volumes:
    #  - ./server/src:/app/src
    #  - ./server/static:/app/static
    #  - ./server/templates:/app/templates
    networks:
      - internal

  reverse-proxy:
    image: nginx:alpine
    depends_on:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # readonly mount our proxy
    networks:
      - internal
      - external

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - reverse-proxy
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - external
    command: tunnel --no-autoupdate run

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
